#!/usr/bin/env python3
"""Generate 301 redirects for the move from the old WordPress site to this one.

Usage, from the Theme-C-Crimson-Gold folder (or anywhere):

    python scripts/build-redirects.py

Reads redirects.csv (columns: old_path, new_path, match, note) and writes:
  .htaccess                 Apache (mod_alias RedirectMatch), upload to the web root
  nginx-redirects.conf      nginx map + server snippet, include it in the server block

match = exact   -> /old-path and /old-path/ redirect to new_path
match = prefix  -> anything that starts with old_path redirects to new_path
Edit redirects.csv, then re-run this command. Needs only Python 3.8+.
"""
import csv
import os
import re

THEME = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(THEME, "redirects.csv")


def pattern(old, match):
    base = re.escape(old.rstrip("/")) if old != "/" else ""
    return f"^{base}/.*$" if match == "prefix" else f"^{base}/?$"


def main():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8")))
    # exact rules first so they win over the broad prefix rules
    rows.sort(key=lambda r: r["match"] != "exact")

    ht = ["# 301 redirects from the old WordPress URLs (generated by scripts/build-redirects.py",
          "# from redirects.csv - edit the CSV and re-run the script instead of editing this file).",
          "<IfModule mod_alias.c>"]
    for r in rows:
        ht.append(f'  RedirectMatch 301 "{pattern(r["old_path"], r["match"])}" "{r["new_path"]}"')
    ht += ["</IfModule>", "", "# Friendly error page", "ErrorDocument 404 /404.html", ""]
    open(os.path.join(THEME, ".htaccess"), "w", encoding="utf-8", newline="\n").write("\n".join(ht))

    ng = ["# 301 redirects from the old WordPress URLs (generated by scripts/build-redirects.py).",
          "# 1) Put the map block in the http { } context.",
          "map $uri $abinitio_redirect {",
          "    default \"\";"]
    for r in rows:
        ng.append(f'    "~{pattern(r["old_path"], r["match"])}" "{r["new_path"]}";')
    ng += ["}", "",
           "# 2) Inside the server { } block for abinitioindia.com:",
           "#    if ($abinitio_redirect) { return 301 $abinitio_redirect; }",
           "#    error_page 404 /404.html;", ""]
    open(os.path.join(THEME, "nginx-redirects.conf"), "w", encoding="utf-8", newline="\n").write("\n".join(ng))
    print(f"{len(rows)} redirects written to .htaccess and nginx-redirects.conf")


if __name__ == "__main__":
    main()
